### PR TITLE
MBS-8741 don't use included build for samples

### PR DESCRIPTION
**Pull request by dsvoronin**
- [x] screenshot test app (won't do, was broken)
- [x] check publishing

### CODE REVIEW

**Comment by eugene-krivobokov** [comment]
Is it a WIP or ready to review?

**Comment by dsvoronin** [comment]
> Is it a WIP or ready to review?

its wip yes, draft -> ready for review is a one way action, so i added wip when realized that there is work to do

edit: ready now

**Review by eugene-krivobokov — APPROVED** [review]

**Comment by eugene-krivobokov** [comment]
> ready for review is a one way action

What do you mean? PR can be converted to a draft at any time:

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft

**Comment by dsvoronin** [comment]
> > ready for review is a one way action
> 
> What do you mean? PR can be converted to a draft at any time:
> 
> https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft

thanks, i didn't know it

**Comment by sergioboi** [comment]
It will be cool if we add Gradle cache for our infra and checks how buildSrc affects it

**Comment by eugene-krivobokov** [comment]
> It will be cool if we add Gradle cache for our infra and checks how buildSrc affects it

Caching: MBS-10600
Tests: MBS-5623

**Pull request merged**
