### PR TITLE
Move test-runner modules (part 1)

### PR DESCRIPTION
**Pull request by dsvoronin**
As discussed previously: moving test-runner modules to separate subproject

## Motivation

Organizing projects by it's classpath destination (gradle/android-test/etc..) adds more confusion than helps. Work usually happens in single logical project like `test-runner` or `build-checks` projects that could contain multiple modules by itself.

Another advantage of this scheme is that different projects can be actually separated in terms of gradle, e.g. have different `settings.gradle's`. There are multiple projects in this repository which is completely independent.

It will, probably, be possible to open some of projects as separate one's in IDE, reducing system impact and enabling simple commands like `./gradlew test` act as it expected for a single small subproject 

## Roadmap

Decided to separate this work to multiple parts to avoid as much clashes as possible

Part1 (THIS PR): moved whole `:gradle:runner` and `:ci`

Part2 probably finishes work for test-runner modules (all testrunner modules, not used in any other project excluding `cd`)

Part3 ....

### CODE REVIEW

**Comment by eugene-krivobokov** [comment]
Despite the discussion, I'd love to see the issue with motivation and ideas about a roadmap.
It will help to see the idea behind changes, especially for Ruslan.

**Comment by sergioboi** [comment]
I think `instrumentation-tests` is a part of runner too. Do you plan to move it?

**Comment by eugene-krivobokov** [comment]
How do you check that all artifacts will preserve maven coordinates?

**Comment by dsvoronin** [comment]
> How do you check that all artifacts will preserve maven coordinates?

by default it is `project.name` which is not changed

it can be overriden with extension like it runner modules:  https://github.com/avito-tech/avito-android/blob/94fbc46ae8c89e892b4f898ea4ddb2d3bafd3f18/subprojects/gradle/runner/client/build.gradle.kts#L8

**Comment by dsvoronin** [comment]
> I think `instrumentation-tests` is a part of runner too. Do you plan to move it?

yes, there are a lot of modules todo; please read the description about it being a first part

**Review by eugene-krivobokov — APPROVED** [review]

**Comment by eugene-krivobokov** [comment]
> > I think `instrumentation-tests` is a part of runner too. Do you plan to move it?
> 
> yes, there are a lot of modules todo; please read the description about it being a first part

Is it worth to make research to define at least the approximate layout of modules?

I don't know exactly how to help, what will be next or the final goal, and so on. 
Thus, I can't really participate in this process, only observing individual changes.

**Comment by dsvoronin** [comment]
> Despite the discussion, I'd love to see the issue with motivation and ideas about a roadmap.
> It will help to see the idea behind changes, especially for Ruslan.

updated the description

**Pull request merged**
