### PR TITLE
MBS-10547 remove FallbackInterceptor, enable explicit api mode

### PR DESCRIPTION
**Pull request by dsvoronin**
Was trying to stabilize service with fallback to another instance, which is not a right solution;
Service is now pretty stable and this fallback just an overcomplication

Also there was a bug: fallback host used only in part of requests

### CODE REVIEW

**Comment by eugene-krivobokov** [comment]
Add please to the description or commit message a brief explanation about the interceptor changes.
I see the changed code but don't understand the reasons.

**Review by eugene-krivobokov — CHANGES_REQUESTED** [review]
Add please to the description or commit message a brief explanation about the interceptor changes.
I see the changed code but don't understand the reasons.

**Comment by dsvoronin** [comment]
> Add please to the description or commit message a brief explanation about the interceptor changes.
> I see the changed code but don't understand the reasons.

fixed

**Comment by eugene-krivobokov** [comment]
> > Add please to the description or commit message a brief explanation about the interceptor changes.
> > I see the changed code but don't understand the reasons.
> 
> fixed

Sorry, where can I find it?

Screenshot from 2021-02-03 18-18-38
Screenshot from 2021-02-03 18-19-10

**Review by eugene-krivobokov — APPROVED** [review]

**Pull request merged**
