### PR TITLE
Remove deprecation from doesNotExist check

### PR DESCRIPTION
**Pull request by lukaville**
There are cases when it's not possible to check negative scenarios without `doesNotExist` check, therefore it would be better to remove the deprecation as there are no alternatives.

### CODE REVIEW

**Comment by eugene-krivobokov** [comment]
> There are cases when it's not possible to check negative scenarios without `doesNotExist` check, therefore it would be better to remove the deprecation as there are no alternatives.

Agree, sometimes we have no choice. But we don't want to encourage using this check.
This is why it has been marked as deprecated.

Do we have another option to show this warning? Maybe custom lint check? We've discussed lint checks for many reasons.

**Comment by sergioboi** [comment]
Deprecation with `Level.Warning` will be enough. And we can clarify our message in Deprecated

**Comment by eugene-krivobokov** [comment]
> Deprecation with `Level.Warning` will be enough. And we can clarify our message in Deprecated

LGTM

**Comment by lukaville** [comment]
OK, warning deprecation level is set by default, so I just translated the message

**Review by eugene-krivobokov — APPROVED** [review]

**Review by dsvoronin — APPROVED** [review]

**Pull request merged**
