### PR TITLE
MBS-8452 update gradle 6.2.1 -> 6.3

### PR DESCRIPTION
**Pull request by dsvoronin**
https://docs.gradle.org/6.4/release-notes.html
https://docs.gradle.org/6.3/release-notes.html

### CODE REVIEW

**Comment by eugene-krivobokov** [comment]
Is it compatible with AGP 3.6.x?

**Review by eugene-krivobokov — APPROVED** [review]

**Review by int02h — APPROVED** [review]

**Comment by dsvoronin** [comment]
6.4 behavior change:

`gradle.taskGraph.whenReady` called on `--dry-run`, was not a case in 6.3

**Comment by dsvoronin** [comment]
rollback to 6.3; will update one by one

**Comment by dsvoronin** [comment]
> Is it compatible with AGP 3.6.x?

API - yes, not sure about implementation; will test; revert is easy

**Pull request merged**
